services:
  server:
    container_name: neyrox-agent
    image: docker.telepat.online/agents-neyrox-image:server-latest
    restart: unless-stopped
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env

  worker:
    container_name: neyrox-worker
    image: docker.telepat.online/agents-neyrox-image:worker-latest
    restart: unless-stopped
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    depends_on:
      - server
